[package]
name = "portfolio"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
rand = "0.8.5"
rand_distr = "0.4.3"
#rand = {version = "0.8.5", default-features = false, features = ["distributions", "rngs"]}
